if(EXISTS "/mnt/c/Users/kidi/Desktop/MergeSort/runTests[1]_tests.cmake")
  include("/mnt/c/Users/kidi/Desktop/MergeSort/runTests[1]_tests.cmake")
else()
  add_test(runTests_NOT_BUILT runTests_NOT_BUILT)
endif()
