add_test([=[SortArrayTest.AlreadySortedArray]=]  /mnt/c/Users/kidi/Desktop/MergeSort/build/test/runTests [==[--gtest_filter=SortArrayTest.AlreadySortedArray]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.AlreadySortedArray]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Users/kidi/Desktop/MergeSort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.ReverseSortedArray]=]  /mnt/c/Users/kidi/Desktop/MergeSort/build/test/runTests [==[--gtest_filter=SortArrayTest.ReverseSortedArray]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.ReverseSortedArray]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Users/kidi/Desktop/MergeSort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.SingleElementArray]=]  /mnt/c/Users/kidi/Desktop/MergeSort/build/test/runTests [==[--gtest_filter=SortArrayTest.SingleElementArray]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.SingleElementArray]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Users/kidi/Desktop/MergeSort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.RepeatedElementsArray]=]  /mnt/c/Users/kidi/Desktop/MergeSort/build/test/runTests [==[--gtest_filter=SortArrayTest.RepeatedElementsArray]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.RepeatedElementsArray]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Users/kidi/Desktop/MergeSort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.EmptyArray]=]  /mnt/c/Users/kidi/Desktop/MergeSort/build/test/runTests [==[--gtest_filter=SortArrayTest.EmptyArray]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.EmptyArray]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Users/kidi/Desktop/MergeSort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.NegativeNumbersArray]=]  /mnt/c/Users/kidi/Desktop/MergeSort/build/test/runTests [==[--gtest_filter=SortArrayTest.NegativeNumbersArray]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.NegativeNumbersArray]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Users/kidi/Desktop/MergeSort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.MixedNegativePositiveArray]=]  /mnt/c/Users/kidi/Desktop/MergeSort/build/test/runTests [==[--gtest_filter=SortArrayTest.MixedNegativePositiveArray]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.MixedNegativePositiveArray]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Users/kidi/Desktop/MergeSort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.DuplicatesArray]=]  /mnt/c/Users/kidi/Desktop/MergeSort/build/test/runTests [==[--gtest_filter=SortArrayTest.DuplicatesArray]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.DuplicatesArray]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Users/kidi/Desktop/MergeSort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.NegativeDuplicatesArray]=]  /mnt/c/Users/kidi/Desktop/MergeSort/build/test/runTests [==[--gtest_filter=SortArrayTest.NegativeDuplicatesArray]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.NegativeDuplicatesArray]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Users/kidi/Desktop/MergeSort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.MixedDuplicatesArray]=]  /mnt/c/Users/kidi/Desktop/MergeSort/build/test/runTests [==[--gtest_filter=SortArrayTest.MixedDuplicatesArray]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.MixedDuplicatesArray]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Users/kidi/Desktop/MergeSort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.TwoElementsArray]=]  /mnt/c/Users/kidi/Desktop/MergeSort/build/test/runTests [==[--gtest_filter=SortArrayTest.TwoElementsArray]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.TwoElementsArray]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Users/kidi/Desktop/MergeSort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.LargeArrayOver100]=]  /mnt/c/Users/kidi/Desktop/MergeSort/build/test/runTests [==[--gtest_filter=SortArrayTest.LargeArrayOver100]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.LargeArrayOver100]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Users/kidi/Desktop/MergeSort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.LargeMixedArrayOver100]=]  /mnt/c/Users/kidi/Desktop/MergeSort/build/test/runTests [==[--gtest_filter=SortArrayTest.LargeMixedArrayOver100]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.LargeMixedArrayOver100]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Users/kidi/Desktop/MergeSort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  runTests_TESTS SortArrayTest.AlreadySortedArray SortArrayTest.ReverseSortedArray SortArrayTest.SingleElementArray SortArrayTest.RepeatedElementsArray SortArrayTest.EmptyArray SortArrayTest.NegativeNumbersArray SortArrayTest.MixedNegativePositiveArray SortArrayTest.DuplicatesArray SortArrayTest.NegativeDuplicatesArray SortArrayTest.MixedDuplicatesArray SortArrayTest.TwoElementsArray SortArrayTest.LargeArrayOver100 SortArrayTest.LargeMixedArrayOver100)
